<?php
/**
 * Dispatcher for the 'entertainment-law' slug.
 *
 * This slug is used twice: a hub page at /entertainment-law/ and a practice
 * area at /practice-areas/entertainment-law/. WordPress matches page-{slug}.php
 * on the slug alone, so we route on the page's parent here.
 *
 * GENERATED by _build/html-to-php.py — do not hand-edit.
 */
$wa_parent = wp_get_post_parent_id( get_queried_object_id() );
$wa_parent_slug = $wa_parent ? get_post_field( 'post_name', $wa_parent ) : '';
include locate_template(
    $wa_parent_slug === 'practice-areas'
        ? 'page-entertainment-law-area.php'
        : 'page-entertainment-law-pillar.php'
);
